### ISSUE TITLE
Fix: Adding a new sheet should instantly open that same new sheet

### ISSUE THREAD

**Issue by dg-ac** [ironcalc/IronCalc#100]
To add new sheets, we need to click the + icon on the bottom-left corner:
<img width="336" alt="image" src="https://github.com/user-attachments/assets/a2bc2e09-e6ef-47dd-87e8-461fad6b8b6c">

By doing this, I would expect not only to create a new sheet, but **also to instantly open such sheet**.

**Comment by nhatcher** [comment]
Fix, please check

**Comment by dg-ac** [comment]
LGTM, thanks a lot!
