### ISSUE TITLE
Fix: When wrongly renaming existing sheets, the dialog keeps the invalid name

### ISSUE THREAD

**Issue by dg-ac** [ironcalc/IronCalc#103]
This can be seen in the video below:

https://github.com/user-attachments/assets/42e282b4-9949-430b-a9b9-33f5b004be49

Ideally, every time users open the dialog they should see the actual sheet name.

**Comment by nhatcher** [comment]
Fixed, please check

**Comment by dg-ac** [comment]
Great, looks fixed. 

Although I see a new issue here: when renaming sheets, if we don't change anything but click the 'Save' button, an error message prompts on top:
<img width="447" alt="image" src="https://github.com/user-attachments/assets/090ef87f-8488-47fe-afe5-f77e511ac03d">

I think this should only be shown if the name is used by another sheet.

**Comment by nhatcher** [comment]
Fix, please check

**Comment by dg-ac** [comment]
LGTM
