### ISSUE TITLE
Fix: Can't easily select cells in other sheets to reference them in formulas

### ISSUE THREAD

**Issue by dg-ac** [ironcalc/IronCalc#104]
Maybe this is more a future feature but at the moment it's not possible to reference cells in other sheets (eg: `=SUM(Sheet1!A1,Sheet1!A2)`) just by clicking. It has to be manually typed at the moment.

Another issue here is that when manually typing a reference in a different sheet, the same cells in the current sheet are highlighted.

More details in this video:

https://github.com/user-attachments/assets/4bdeccd4-8cd1-475e-bb97-a7e0a4637900

**Comment by nhatcher** [comment]
Fixed.

**Comment by dg-ac** [comment]
The second part is fixed. What about referencing other sheets? Is it more a feature than a bug?

**Comment by nhatcher** [comment]
Reopening.

But it does work for me :/

**Comment by dg-ac** [comment]
Oh, just tested it again and works as expected. Thank you! I'll close the issue now.
