### ISSUE TITLE
Fix: Ranges are not correctly displayed in the formula bar

### ISSUE THREAD

**Issue by dg-ac** [ironcalc/IronCalc#105]
Single cells are correctly displayed:
<img width="342" alt="image" src="https://github.com/user-attachments/assets/43ff28c9-3dbd-4ce1-a06b-dfb3abaf78aa">

However, ranges are not:
<img width="295" alt="image" src="https://github.com/user-attachments/assets/74b0f66a-4666-43e8-93ff-acd586f816fd">

Ideally, for this second image we should show A1:B3 instead of just A1.

**Comment by nhatcher** [comment]
Fixed.

**Comment by dg-ac** [comment]
Works!
