### ISSUE TITLE
Fix: Pressing the 'Delete' key doesn't delete multiple cells

### ISSUE THREAD

**Issue by dg-ac** [ironcalc/IronCalc#108]
Ideally, selecting multiple cells with content inside, and hitting the key 'Delete' should erase the content inside all these cells.

At the moment, it only deletes the first cell of the range:

https://github.com/user-attachments/assets/25aaa04d-53c2-42b1-9a53-863e36901d58

**Comment by nhatcher** [comment]
Hmm, this does work for me. Maybe mixing DELETE with BACKSPACE?

Note that we follow Excel's conventions here:

* DELETE key will delete all the cells
* BACKSPACE will delete the content of one and start edtiting

**Comment by dg-ac** [comment]
Oh, I see! Closing the issue then.
