### ISSUE TITLE
Fix: Imported workbooks should use the file name as title

### ISSUE THREAD

**Issue by dg-ac** [ironcalc/IronCalc#111]
This one is self explanatory. At the moment, the workbook title is generated by IronCalc:
<img width="628" alt="image" src="https://github.com/user-attachments/assets/0518752f-1584-4d4e-a79a-e261475fe5b1">

Ideally, we should use as title the name of the file updated.

**Comment by nhatcher** [comment]
Fixed, please test

**Comment by dg-ac** [comment]
Fantastic. Works for me.

**Comment by dg-ac** [comment]
Sorry, reopening. I feel the extension (`.xlsx`, for example) shouldn't be part of the title. If I import a worksheet called `file.xlsx` and download it again, the name of the new file will be `file.xlsx.xlsx`, which feels odd. What do you think?

**Comment by nhatcher** [comment]
True, fixed.

**Comment by dg-ac** [comment]
LGTM!
