### ISSUE TITLE
add `test` as an additional target in Makefile

### ISSUE THREAD

**Issue by mcarifio** [ironcalc/IronCalc#131]
This issue is really an excuse to say this is a great idea and I plan to track the project. I'll also note in passing that in the 2010's there were a bunch of Iron${thing} projects that added interesting languages to the dotnet platform, e.g. IronPython. You might suffer some "brand confusion" from them. Or I'm dating myself. Pick one.

Commit `98dc557a017b2ad640fb46eece17afda14177e59` built right out of the box -- very nice -- but I didn't read carefully enough and issued `make test` rather than `make tests`. This is a small thing and yes, it was pilot error on my part. But as I understand it, `make test` is the usual target/convention and some builders aren't careful readers (cough, cough, "me").

**Comment by nhatcher** [comment]
Hi @mcarifio! Thanks for opening the ticket!

True about IronThings... Difficult to pick a completely new name with no references to anything existing these days :).

Hopefully there is no confusion.

WRT to `make tests` vs `make test` I chose the former to tell it apart easier from `cargo test`. I rather have just one than two ways of running the test. I will close the ticket for now, but if it causes confusion I will just update it to `make test`. Hope that ok!
