### ISSUE TITLE
Adding Formatter Pluggin to IronCalc

### ISSUE THREAD

**Issue by varuntumbe** [ironcalc/IronCalc#133]
As @AndrooFrowns mentioned, It would be a nice idea to add a automated formatter pluggin https://github.com/marketplace/actions/rust-rustfmt-check

**Comment by nhatcher** [comment]
Hey, isn't this already achieved doing `make tests` in the CI? Manually you have to write `make lint`:

https://github.com/ironcalc/IronCalc/blob/main/Makefile#L2

**Comment by varuntumbe** [comment]
> Hey, isn't this already achieved doing `make tests` in the CI? Manually you have to write `make lint`:
> 
> https://github.com/ironcalc/IronCalc/blob/main/Makefile#L2

Hi @nhatcher I was thinking of automating this formatting step automatically.

Like I have seen in some other projects where even if you push the commits without formatting it, it will automatically push one more commit with formatting all the code.

I thought that's what Androo also meant.

**Comment by nhatcher** [comment]
Ah! Understood. Not a bad idea, but not now please. I prefer those commits done manually for the time being.

But I will keep an eye on this in case it becomes an issue
