### ISSUE TITLE
Weird behavior using absolute and mixed references (dollar sign)

### ISSUE THREAD

**Issue by marthadev** [ironcalc/IronCalc#155]
The range A$1:A2 gets reformatted into the different and useless A2:A$1

https://github.com/user-attachments/assets/13ebe99e-86b2-4821-8d15-fc09cfb2df70

Also, $A1:A$2 somehow becomes A1:$A$2

**Comment by nhatcher** [comment]
Fixed and deployed.

Thanks again!

**Comment by marthadev** [comment]
Great!
