### ISSUE TITLE
Fix: Webapp columns can be resized to "negative"

### ISSUE THREAD

**Issue by enjoythecode** [ironcalc/IronCalc#165]
It is possible to drag the right-border of the column to the left of the left border (as if the width was "negative", so-to-say), which breaks the UI in multiple ways.

**Demonstration:**

![ironcalc-negative_column_width](https://github.com/user-attachments/assets/27ad4744-3042-44b7-9373-144aa40deca9)

**Expected behavior:**

Limit the minimum column size.

**Comment by enjoythecode** [comment]
Hmm, the rust back-end should probably reject a negative width? @nhatcher do you think this should be handled on the UI or the "backend"? I am happy to make my first PR on this task.

**Comment by enjoythecode** [comment]
Same issue exists with rows.

**Comment by nhatcher** [comment]
Hi @enjoythecode , this is a great first task. It should be handled in both places.

Around:

https://github.com/ironcalc/IronCalc/blob/main/base/src/worksheet.rs#L300

insert:

```rust
if width < 0.0 {
    return Err(format!("Cannot set a negative width: {width}"));
}
```

you will need to add a regression test in:

https://github.com/ironcalc/IronCalc/blob/main/base/src/test/test_column_width.rs

In the front:

https://github.com/ironcalc/IronCalc/blob/main/webapp/src/components/worksheet.tsx#L107

Maybe something like:

```js
if (width > 0) {
      model.setColumnWidth(sheet, column, width);
      worksheetCanvas.current?.renderSheet();
}
```

Something similar for rows.

Please add an entry to the CHANGELOG under "fixed".

Many thanks!

**Comment by nhatcher** [comment]
This is fixed now
