### ISSUE TITLE
Excel Compatibility: or Function

### ISSUE THREAD

**Issue by gian-hancock** [ironcalc/IronCalc#175]
# Summary
IronCalc allows `=or()` (no parameters), while Excel does not. This means it's possible to export xlsx files from IronCalc that Excel can't load correctly.

## IronCalc Behaviour
- `or` takes any number of parameters, `=or()` returns FALSE.

## Excel Behaviour
- The `or` formula takes a minimum of 1 parameters
- In Excel (365) if you type in `=or()` you get an error and it doesn't accept the formula:  
   ![image](https://github.com/user-attachments/assets/7a9f6fbb-fd4d-4314-901e-700c823d9f48)
- If you you load an xlsx containing `=or()` exported from IronCalc, Excel will treat the file as corrupted:   
   ![image](https://github.com/user-attachments/assets/4793ac7e-28a4-4b36-ab96-385630d3a497)
- If you recover the file, it replaces the formula with the text FALSE
   ![image](https://github.com/user-attachments/assets/38a3982b-6e9f-48d1-90f1-52ccb5c30c00)

## LibreOffice Calc Behaviour
Like Excel, Calc requires at least one argument, however the UI doesn't prevent you from entering `=or()`. Instead you get an error in the cell `Err511`. If you try to save the file as an XLSX, you get an error:
![image](https://github.com/user-attachments/assets/034fcd48-8972-4511-a246-a61f85c60743)

# Underlying Issue
Similar situations can be encountered in other scenarios where Excel disallows an invalid formula, such as setting a cell to `=/`. The core issue is that Excel prevents some formulas from being created in the first place, while IronCalc does not.

# Potential Solutions
Solutions which come to mind for the the broader issue on how to handle invalid formulas that are incompatible with Excel:
1. Follow the Calc approach and disallow saving to XLSX when an incompatible formula is present.
2. Maintain the current export method. Excel will report an error, but the user can "recover" the file with the offending formulas removed and replaced with their calculated values.
3. At XLSX export time, remove incompatible formulas and replace them with calculated values, potentially with a warning message.
4. Implement logic similar to Excel, preventing the creation of these invalid formulas in the first place.

**Comment by gian-hancock** [comment]
Hi there, I found this while going through and adding more tests for functions (we discussed this on [Discord](https://discord.com/channels/1206947691058171904/1206947691058171907/1314182018640117801)). There are likely more cases like this, but I haven't looked yet.

If the fix is simply to update `if` to have the same parameter requirements as Excel, I'm happy to submit a PR.

**Comment by gian-hancock** [comment]
Updated the Issue description with "LibreOffice Calc Behaviour", "Underlying Issue", and "Potential Solutions" sections.

**Comment by nhatcher** [comment]
Hi @gian-hancock , thanks for the detailed issue and description. IronCalc's current solution is to throw `#ERROR!`.

Regrettably this is not implemented correctly in functions like `OR`. I am not too worried about producing workbooks that have some issues when opening in Excel as they are  broken in the first place. 

The fix in this case is:

```rust
if args.is_empty() {
 return CalcResult::new_error(Error::ERROR, cell, "OR needs at least one argument".to_string());
}
```
in:

https://github.com/ironcalc/IronCalc/blob/main/base/src/functions/logical.rs#L139

and add a test similar to:

https://github.com/ironcalc/IronCalc/blob/main/base/src/test/test_fn_financial.rs#L52

come the day in the future we could indicate some Excel incompatibilities.

If you feel like doing a PR for the local function, that would be awesome!

This is what google sheets does:

![image](https://github.com/user-attachments/assets/288060a7-5892-452f-bec4-e61a07fdc889)

Zoho returns #NAME! which is weird.

I actually like IronCalc's behaviour. Returning `#ERROR!` signalling an error in the formula, same behaviour as Calc.

PS: I will think a bit more about what to do on saving.
