### ISSUE TITLE
Webapp: Last remaining sheet can not be deleted but the "Delete" icon is clickable

### ISSUE THREAD

**Issue by enjoythecode** [ironcalc/IronCalc#192]
![image](https://github.com/user-attachments/assets/b5f16b69-89e7-430c-84a0-ced489a2f7dd)

The "delete" icon should be grayed out to communicate that the last sheet may not be cleared. Perhaps also add a tooltip explaining this behavior?

**Comment by nhatcher** [comment]
FYI: @dg-ac

**Comment by enjoythecode** [comment]
I'm happy to implement this once there is a design.

**Comment by dg-ac** [comment]
Hey @enjoythecode,

Good catch! What you suggest makes total sense. That said, this is how the disabled state should look like:

<img width="326" alt="image" src="https://github.com/user-attachments/assets/20321782-5f8a-419b-84a2-c60677ed91e8" />

Pretty much same as the default one but using grey-400 (#BDBDBD) as color for icons and text. I think this should be enough, so we probably don't need to add a tooltip on hover.

Let me know if you need anything else! 🙂

D

**Comment by nhatcher** [comment]
@enjoythecode , go ahead and fix this if you like. Thanks!

**Comment by enjoythecode** [comment]
Will do, I should get a chance tomorrow. Thanks D for design.

**Comment by enjoythecode** [comment]
Fixed by #200 + #206
