### ISSUE TITLE
Webapp: cut across sheets does not remove the original data

### ISSUE THREAD

**Issue by enjoythecode** [ironcalc/IronCalc#193]
![ironcalc-cut_across_sheets](https://github.com/user-attachments/assets/4e131543-5251-4b83-aef3-d5b3bdbe15c3)

Is this expected behavior? I noticed that the code path for this actually does not include a way to communicate the sheet, so maybe it was intended? I don't have a copy of Excel so I can't test. @nhatcher

**Comment by enjoythecode** [comment]
I am also happy to implement this if confirmed as a bug.

**Comment by nhatcher** [comment]
This is a bug, but let me handle it, I actually need to change the clipboard type
